apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: example-app-v2
  name: example-app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: example-app-v2
