apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: example-app-v2
  name: example-app-v2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: example-app-v2
    spec:
      containers:
      - env:
        - name: APPRES
          value: "New Environment Variable"
        image: idanshahar/example-app:latest
        name: example-app
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-registry
      restartPolicy: Always
